apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-devops-develop
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    namespace: test-devops-develop
    server: https://kubernetes.default.svc
  source:
    path: helms/test-devops
    repoURL: https://github.com/extosoft-devsecops/test-devops-gitops.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-develop.yaml
      parameters:
        - name: app.replicaCount
          value: '2'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
