apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-devops.fullname" . }}-app
  labels:
    {{- include "test-devops.app.labels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "test-devops.app.selectorLabels" . | nindent 4 }}