{{- if .Values.graphite.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-devops.fullname" . }}-graphite
  labels:
    {{- include "test-devops.graphite.labels" . | nindent 4 }}
  {{- with .Values.graphite.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.graphite.service.type }}
  ports:
    - port: {{ .Values.graphite.service.httpPort }}
      targetPort: 80
      protocol: TCP
      name: http-ui
    - port: {{ .Values.graphite.service.statsdPort }}
      targetPort: {{ .Values.graphite.service.statsdPort }}
      protocol: UDP
      name: statsd-udp
    - port: {{ .Values.graphite.service.carbonPort }}
      targetPort: {{ .Values.graphite.service.carbonPort }}
      protocol: TCP
      name: carbon-line
  selector:
    {{- include "test-devops.graphite.selectorLabels" . | nindent 4 }}
{{- end }}