apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cf-root-app-project
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
